### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by Glenn032787** [UBC-MDS/sanityze#31]
**Congratulations on finishing milestone 1!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  

We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
If anything is unclear, please feel free to ask questions in this issue thread.

## 1. Team work contract

Good Job!

## 2. Create project structure for the python project (40 points)
- [x] #35

*Comment:* Missing CONTRIBUTOR.md in repo. You could use [this](https://github.com/ttimbers/convertempPy/blob/master/CONTRIBUTORS.md) as an example for what to include in this file.

## 3. Function specifications (20 points)
- [x] Docstrings are incomplete or not [follow the standards](https://py-pkgs.org/06-documentation#docstrings) - **quality -1**

*Comment:* The function and parameter description is very clearly. A small improvement would be to include a small example in the docstring.

## 4. Manage issues (10 points)
- [x] #40

## 5. Specific expectations for this milestone are: (10 points)

Good Job!

## 6. Submission instructions (10 points)
Good Job!

**Comment by tzoght** [comment]
Thanks @Glenn032787, Regarding Item 2. We have outlined the list of contributors in the README.md, as instructed by the milestone 1 link (https://pages.github.ubc.ca/mds-2021-22/DSCI_524_collab-sw-dev_students/materials/assignments/milestone1.html) I asked int he lab and I was told that as long as I have the name of the contributors along with their github ids as links we should be fine.

**Comment by Glenn032787** [comment]
Hey! I asked the instructors and they said that as it is best practice, they want you to include a `CONTRIBUTOR.md` file. As you mentioned it in the README, I will reduce the points by 2.5 only but make sure to include it in the next milestone.

**Comment by tzoght** [comment]
Hi @Glenn032787  I have added CONTRIBUTORS.md as suggest, and thanks for looking into this

**Comment by caesarw0** [comment]
closing issue as completed
