### ISSUE TITLE
Discuss license

### ISSUE THREAD

**Issue by tzoght** [UBC-MDS/sanityze#48]
**Question from milestone 4**:  Examine the license for your project and consider whether this is the choice you want to make, or whether you want to change the license. Discuss and reason the license choice by opening issues in both Python and R repositories. As it is likely to be a very similar discussion for both projects, one of these issues can just link to the other issue where it is thoroughly discussed.

**Comment by xXJohamXx** [comment]
duplicate issue, see [https://github.com/UBC-MDS/sanityze/issues/51](url)
